NAME: SAKSHI JADHAV

ROLL NO.: 23107043

BATCH: C

CLASS: TY-AIDS-A

<h4>Clustering 2D Data Using ART1-

1. Implement the ART1 algorithm for binary input data.
2. Given a set of binary vectors, cluster them into categories based on similarity.
3. Use vigilance parameter (ρ) to control cluster formation.</h4>

In [3]:
import numpy as np

In [4]:
rho = 0.4 
lr = 2     
n = 4  
m = 3 

In [5]:
inputs = np.array([
    [0, 0, 0, 1],
    [0, 1, 0, 1],
    [0, 0, 1, 1],
    [1, 0, 0, 0]
])

In [6]:
bij = np.full((n, m), 1 / (1 + n))
tji = np.ones((m, n))

In [7]:
print("Initial Bottom-Up Weights:\n", bij)
print("\nInitial Top-Down Weights:\n", tji)

Initial Bottom-Up Weights:
 [[0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]]

Initial Top-Down Weights:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
cluster_assignments = []

In [9]:
for idx, S in enumerate(inputs):
    print(f"\nInput S{idx+1} = {S}")

    # Step 3.1: Compute net input for each cluster
    y = np.dot(S, bij)
    winner = np.argmax(y)  # Cluster with maximum activation
    print(f"Net inputs: {y}, Winner: Y{winner+1}")

    # Step 3.2: Recompute activation
    x = S * tji[winner]
    print(f"Recomputed x = {x}")

    # Step 3.3: Vigilance Test
    match = np.sum(x) / (np.sum(S) + 1e-6)
    print(f"Vigilance ratio = {match:.2f}")

    if match >= rho:
        print("Vigilance passed! so Update weights")
        # Update Bottom-Up weights
        for i in range(n):
            bij[i][winner] = (lr * x[i]) / ((lr - 1) + np.sum(x))
        # Update Top-Down weights
        tji[winner] = x
        cluster_assignments.append((f"S{idx+1}", f"Y{winner+1}"))
    else:
        print("Vigilance failed! so Skip or create new cluster")
        cluster_assignments.append((f"S{idx+1}", "No cluster (new one may form)"))

    print("\nUpdated Bottom-Up Weights:\n", bij)
    print("Updated Top-Down Weights:\n", tji)


Input S1 = [0 0 0 1]
Net inputs: [0.2 0.2 0.2], Winner: Y1
Recomputed x = [0. 0. 0. 1.]
Vigilance ratio = 1.00
Vigilance passed! so Update weights

Updated Bottom-Up Weights:
 [[0.  0.2 0.2]
 [0.  0.2 0.2]
 [0.  0.2 0.2]
 [1.  0.2 0.2]]
Updated Top-Down Weights:
 [[0. 0. 0. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Input S2 = [0 1 0 1]
Net inputs: [1.  0.4 0.4], Winner: Y1
Recomputed x = [0. 0. 0. 1.]
Vigilance ratio = 0.50
Vigilance passed! so Update weights

Updated Bottom-Up Weights:
 [[0.  0.2 0.2]
 [0.  0.2 0.2]
 [0.  0.2 0.2]
 [1.  0.2 0.2]]
Updated Top-Down Weights:
 [[0. 0. 0. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Input S3 = [0 0 1 1]
Net inputs: [1.  0.4 0.4], Winner: Y1
Recomputed x = [0. 0. 0. 1.]
Vigilance ratio = 0.50
Vigilance passed! so Update weights

Updated Bottom-Up Weights:
 [[0.  0.2 0.2]
 [0.  0.2 0.2]
 [0.  0.2 0.2]
 [1.  0.2 0.2]]
Updated Top-Down Weights:
 [[0. 0. 0. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Input S4 = [1 0 0 0]
Net inputs: [0.  0.2 0.2], Winner: Y2
Recompu

In [15]:
# Final Output
print("\nFinal Bottom-Up Weights:\n", bij)
print("\nFinal Top-Down Weights:\n", tji)

#Cluster conclusion
print("\nConclusion:")
for s, c in cluster_assignments:
    print(f"{s} belongs to {c}")


Final Bottom-Up Weights:
 [[0.  1.  0.2]
 [0.  0.  0.2]
 [0.  0.  0.2]
 [1.  0.  0.2]]

Final Top-Down Weights:
 [[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 1. 1. 1.]]

Conclusion:
S1 belongs to Y1
S2 belongs to Y1
S3 belongs to Y1
S4 belongs to Y2
